version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Starting build step...
      - mkdir -p dist
      - rsync -av --exclude dist ./ dist/
      - cp appspec.yml dist/

artifacts:
  base-directory: dist
  files:
    - '**/*'
